version: "3.8"

volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    container_name: postgres
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_network
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/app/collected_static
      - media:/app/media
    networks:
      - kittygram_network
    restart: always

  frontend:
    container_name: frontend
    env_file: .env
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - static:/app/build
    networks:
      - kittygram_network
    restart: always

  gateway:
    container_name: gateway
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html
      - media:/var/www/media
    ports:
      - "80:80"
    networks:
      - kittygram_network
    restart: always

networks:
  kittygram_network:
    driver: bridge
