volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    container_name: postgres
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_network
  backend:
    container_name: backend
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/app/collected_static
      - media:/app/media
    networks:
      - kittygram_network
  frontend:
    container_name: frontend
    env_file: .env
    volumes:
      - static:/app/build
    networks:
      - kittygram_network

  gateway:
    container_name: gateway
    depends_on:
      - backend
    volumes:
      - static:/usr/share/nginx/html
      - media:/var/www/media
    ports:
      - "80:80"
    networks:
      - kittygram_network

networks:
  kittygram_network:
    external: false